# Generated by Django 5.0.2 on 2026-04-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_ESPERA', 'En espera'), ('APROBADA', 'Aprobada'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
    ]
