# Generated by Django 5.0.2 on 2026-04-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='primera_entrada_mexico',
            field=models.BooleanField(default=False, verbose_name='Primera entrada a México'),
        ),
    ]
