# Generated by Django 5.0.2 on 2026-04-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('muelles', '0002_espacio_espacio_uq_espacio_muelle_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='pos_fin',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='pos_inicio',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='espacios',
            field=models.ManyToManyField(related_name='asignaciones', to='muelles.espacio'),
        ),
    ]
