# Generated by Django 5.0.2 on 2026-04-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_remove_asignacion_pos_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
