# Generated by Django 5.0.2 on 2026-04-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tam_maximo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_espacios', models.PositiveIntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('coordenada_x', models.DecimalField(decimal_places=6, max_digits=10)),
                ('coordenada_y', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'verbose_name': 'Muelle',
                'verbose_name_plural': 'Muelles',
                'db_table': 'muelle',
                'ordering': ['nombre'],
            },
        ),
    ]
