# Generated by Django 5.0.2 on 2026-04-11 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('pos_x', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pos_y', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('es_pasillo', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('muelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='muelles.muelle')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'db_table': 'espacio',
                'ordering': ['muelle', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='espacio',
            constraint=models.UniqueConstraint(fields=('muelle', 'numero'), name='uq_espacio_muelle_numero'),
        ),
    ]
