# Generated by Django 5.0.2 on 2026-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muelles', '0002_espacio_espacio_uq_espacio_muelle_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='muelle',
            name='rotacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
