# Generated by Django 5.0.2 on 2026-04-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muelles', '0003_muelle_rotacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaTierra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.TextField()),
                ('color', models.CharField(default='#7ab648', max_length=7)),
                ('nombre', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Zona de tierra',
                'verbose_name_plural': 'Zonas de tierra',
                'db_table': 'zona_tierra',
            },
        ),
    ]
