# Generated by Django 5.0.2 on 2026-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muelles', '0004_zonatierra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muelle',
            name='rotacion',
        ),
        migrations.AddField(
            model_name='espacio',
            name='rotacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
