# Generated by Django 5.0.2 on 2026-04-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muelles', '0005_remove_muelle_rotacion_espacio_rotacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='espacio',
            name='uq_espacio_muelle_numero',
        ),
        migrations.AlterField(
            model_name='espacio',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='espacio',
            constraint=models.UniqueConstraint(condition=models.Q(('es_pasillo', False)), fields=('muelle', 'numero'), name='uq_espacio_muelle_numero'),
        ),
    ]
