# Generated by Django 5.0.2 on 2026-04-11 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muelles', '0006_remove_espacio_uq_espacio_muelle_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaMuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pos_y', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('texto', models.CharField(max_length=80)),
                ('tamanio', models.PositiveIntegerField(default=14)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('muelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta', to='muelles.muelle')),
            ],
            options={
                'verbose_name': 'Etiqueta de muelle',
                'verbose_name_plural': 'Etiquetas de muelles',
                'db_table': 'etiqueta_muelle',
            },
        ),
    ]
